services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mlflow}
      POSTGRES_USER: ${POSTGRES_USER:-mlflow}
      POSTGRES_DB: ${POSTGRES_DB:-mlflowdb}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mlflow:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
    volumes:
      - mlflow_artifacts:/home/ml/artifacts
    command:
      - server
      - --host=0.0.0.0
      - --port=5000
      - --backend-store-uri=${BACKEND_STORE_URI:-postgresql://${POSTGRES_USER:-mlflow}:${POSTGRES_PASSWORD:-mlflow}@db:5432/${POSTGRES_DB:-mlflowdb}}
      - --default-artifact-root=${ARTIFACT_ROOT:-file:///home/ml/artifacts}

volumes:
  mlflow_artifacts:
